sql:
  dialect: POSTGRES

spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/dev_undying_db
    username: dev_user
    password: dev_password
    driverClassName: org.postgresql.Driver

  # only for development (on production must be commented)
  flyway:
    clean-disabled: false

  docker:
    compose:
      enabled: false

springdoc:
  swagger-ui:
    enabled: true

logging:
  level:
    org:
      springframework:
        security: debug