sql:
  dialect: POSTGRES

spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/dev_undying_db
    username: dev_user
    password: dev_password
    driverClassName: org.postgresql.Driver

  # only for development (on production must be commented)
  flyway:
    clean-on-validation-error: true
    clean-disabled: false

logging:
  level:
    org:
      springframework:
        security: debug